sudo: true
language: android
dist: trusty
install: true
addons:
  sonarcloud:
    organization: federicoiosue-github
    token: $SONAR_TOKEN
    branches:
    - develop
jdk:
- oraclejdk8
branches:
  only:
  - develop
  - master
  - /^feature/.*$/
  - /^hotfix/.*$/
  - /^release/.*$/
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
script: 
  - ./gradlew clean build jacocoTestReport sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
